# Change these first
owner: Oreoxmt
repo: status-page

sites:
  - name: Working Day Calculator
    url: https://tool.oreo.life/workcalc/
  - name: Holiday Announcement Parser
    url: https://tool.oreo.life/holiparse/
  - name: Automatic Release Scheduler
    url: https://tool.oreo.life/autosched/

assignees:
  - Oreoxmt

status-website:
  cname: v1.oreo.life
  baseUrl: /tool
  logoUrl: https://raw.githubusercontent.com/Oreoxmt/oreo.life-v2/main/website/static/img/logo.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
